name: minichatapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/generated/
