// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBme-JH-wxCB2Fck88nMZsfFhBfyeq4FAY',
    appId: '1:468809539663:android:bdabc87ab0435e08758a3a',
    messagingSenderId: '468809539663',
    projectId: 'mini-chat-app-d5c27',
    storageBucket: 'mini-chat-app-d5c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARUWPpQoZwdesm0F70v5Yl_VuCsNKbPTg',
    appId: '1:468809539663:ios:9856c25fbdb7a468758a3a',
    messagingSenderId: '468809539663',
    projectId: 'mini-chat-app-d5c27',
    storageBucket: 'mini-chat-app-d5c27.firebasestorage.app',
    androidClientId: '468809539663-smf874otc1c0ha152k0emo55qm78b20t.apps.googleusercontent.com',
    iosClientId: '468809539663-jrpdlvu161j8vbre83a3ecpfjb0iercr.apps.googleusercontent.com',
    iosBundleId: 'com.example.minichatapp',
  );
}
